<a href="https://colab.research.google.com/github/lsvignesh12596/TensorFlow/blob/main/TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

# tf.Constant

In [12]:
# scalar
scalar = tf.constant([10,7])
scalar

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [11]:
scalar.ndim

1

In [18]:
# vector
vector = tf.constant([[10,7,1],[7,10,0]])
vector

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10,  7,  1],
       [ 7, 10,  0]], dtype=int32)>

In [19]:
vector.ndim

2

In [15]:
# vector
vector = tf.constant([[10,7,3],
                      [3,7,10],
                      [1,1,1]])
vector

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  3],
       [ 3,  7, 10],
       [ 1,  1,  1]], dtype=int32)>

In [16]:
vector.ndim

2

In [20]:
# tensor
tensor = tf.constant([[[10,7,3],
                     [1,1,1],
                     [0,7,3]],
                     [[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
tensor

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[10,  7,  3],
        [ 1,  1,  1],
        [ 0,  7,  3]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]]], dtype=int32)>

In [32]:
tensor.ndim

3

# tf.Variable

In [24]:
# alternate scalar
a_scalar = tf.Variable([10,7])
a_scalar

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [26]:
a_scalar.shape

TensorShape([2])

In [27]:
# alternate vector
a_vector = tf.Variable([[10, 7],
                       [11, 3]])
a_vector

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[10,  7],
       [11,  3]], dtype=int32)>

In [28]:
a_vector.shape

TensorShape([2, 2])

In [33]:
# alternate tensor
a_tensor = tf.Variable([[[10,7],
                       [1,3]],
                       [[2,5],
                       [3,8]],
                        [[5,6],
                        [7,8]]])
a_tensor

<tf.Variable 'Variable:0' shape=(3, 2, 2) dtype=int32, numpy=
array([[[10,  7],
        [ 1,  3]],

       [[ 2,  5],
        [ 3,  8]],

       [[ 5,  6],
        [ 7,  8]]], dtype=int32)>

In [34]:
a_tensor.shape

TensorShape([3, 2, 2])

# difference b/w tf.constant and tf.Variable

1. tf.constant values cannot be changed
2. tf.Variable values can be changed using "assign" method

In [35]:
random_var = tf.constant([10,7])
random_var

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [36]:
random_var[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [37]:
random_var[0] = 3

TypeError: ignored

In [38]:
random_var[0].assign(3)

AttributeError: ignored

In [39]:
random_var = tf.Variable([10,7])
random_var

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [40]:
random_var[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [41]:
random_var[0] = 3

TypeError: ignored

In [42]:
random_var[0].assign(3)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([3, 7], dtype=int32)>